### ISSUE TITLE
my authenticator all code blank

### ISSUE THREAD

**Issue by jerry2201** [Sneezry/authenticator#244] opened 2018-01-28 18:41 UTC
dear admin
good evening

can u solved my problem authentic...
i can login without thats...

thanks for your attention

**Comment by mymindstorm** [comment] 2018-01-28 18:42
Duplicate of #223

Your codes are safe, fix coming soon

**Comment by Alternating** [comment] 2018-01-28 18:42
I'm having the same issue. Codes were there on the google chrome app. I went to click on it again and now no codes are displayed and I cannot access any of the settings.

**Comment by morlin-denmark** [comment] 2018-01-28 18:57
Same problem here.

**Comment by avlion82** [comment] 2018-01-28 19:00
I also have this problem, all the codes are gone. The gear does not respond. Removed anew I did not help

**Comment by digi1989** [comment] 2018-01-28 19:06
Im having same issue. Is it being worked on? Didnt want to remove my extension since i didnt write down my backup codes

**Comment by galycar** [comment] 2018-01-28 19:07
I have the same problem, please help. Thanks

**Comment by hartatyfatshaf** [comment] 2018-01-28 19:39
me too, my auth not seen, blank

**Comment by bphyak** [comment] 2018-01-28 19:46
whats going on ? i am having same problem

**Comment by Sneezry** [comment] 2018-01-28 21:05
4.20 has been released, your extension should be upgraded automatically.

If you need upgrade immediately, open chrome://extensions/, check Developer mode, then click Update extensions now.

<img width="803" alt="qq20180129-050406 2x" src="https://user-images.githubusercontent.com/1621293/35487026-dead6726-04b1-11e8-8cd1-bfc60a306df9.png">

**Closed** 2018-01-30 17:56 UTC
