### ISSUE TITLE
已有三个otp，再添加新otp，会覆盖最后一个otp

### ISSUE THREAD

**Issue by stevenzhoutao** [Sneezry/authenticator#32] opened 2015-09-29 08:00 UTC
已有三个otp，再添加新otp，会覆盖旧的最后一个otp

**Comment by Sneezry** [comment] 2015-09-29 08:16
![](https://cloud.githubusercontent.com/assets/1621293/10158453/cf390d64-66c4-11e5-9f2e-f1d94a6a0550.png)

可以提供更多的信息吗，我测试是可以添加三个以上的账号的，可能与某个密钥格式相关

[Origin Issue: 3 accounts have been added, and new account will cover the last one]
Could you please provide more information? I have tested and added more than 3 accounts successfully. Maybe this issue is caused by some special format secret.

**Comment by Sneezry** [comment] 2015-11-06 06:33
This issue has been closed as we didn't receive further feedback over a month.

**Closed by Sneezry** 2015-11-06 06:33 UTC
