### ISSUE TITLE
my authenticator is not working

### ISSUE THREAD

**Issue by Varkrey** [Sneezry/authenticator#225] opened 2018-01-28 16:10 UTC
Yesterday I turned off my pc and today, simply my codes disappeared, please help me, it's an emergency.
![2222](https://user-images.githubusercontent.com/35896469/35484270-ed4445ac-0434-11e8-9c2d-f706d575a869.png)

**Comment by mymindstorm** [comment] 2018-01-28 16:11
Duplicate of #223

**Comment by Sneezry** [comment] 2018-01-28 20:56
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.

**Closed** 2018-01-30 18:00 UTC
