### ISSUE TITLE
firefox is not working either for authenticator

### ISSUE THREAD

**Issue by thetree3** [Sneezry/authenticator#227] opened 2018-01-28 16:55 UTC
please please please help me, im locked out from every penny i own! i could this happen... until this is fixed i wont have a single dollar! this is very very bad for me, can not believe this is even happening

**Comment by mymindstorm** [comment] 2018-01-28 16:55
Duplicate of #223

**Comment by Sneezry** [comment] 2018-01-28 20:56
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.

**Comment by thetree3** [comment] 2018-01-28 21:07
everythyng will be all good in one hour?

**Comment by Sneezry** [comment] 2018-01-28 21:16
4.20 has been released, your extension should be upgraded automatically.

If you need upgrade immediately, open chrome://extensions/, check Developer mode, then click Update extensions now.

<img width="803" alt="qq20180129-050406 2x" src="https://user-images.githubusercontent.com/1621293/35487026-dead6726-04b1-11e8-8cd1-bfc60a306df9.png">

**Comment by thetree3** [comment] 2018-01-28 21:17
thank you kind sir

**Comment by thetree3** [comment] 2018-01-28 21:23
sorry to bother u again, but its telling me now that it is encrypted and i needed to enter a passphrase, is this passphrase that number i saved when i first got the authenticator?
or is this somethyng different?

**Comment by Sneezry** [comment] 2018-01-28 21:39
@thetree3 the passphrase should not be changed.

**Comment by thetree3** [comment] 2018-01-28 21:43
ok thank you very much, i got it, its all set i appreciate ur help

**Closed** 2018-01-30 18:00 UTC
