### ISSUE TITLE
Google authenticator not working

### ISSUE THREAD

**Issue by chrisledesco** [Sneezry/authenticator#226] opened 2018-01-28 16:46 UTC
Hello
when i click on my app , i usually see my codes, but now i see nothing , and clicking on the pen and the wheel isnt working 
it was working yesterday 
thanks

**Comment by mymindstorm** [comment] 2018-01-28 16:47
Duplicate of #223

**Comment by adilbek84** [comment] 2018-01-28 16:54
http://joxi.ru/v29NEXyI3o0BeA HELP APPLICATIONS ceased to work ???

**Comment by Sneezry** [comment] 2018-01-28 20:56
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.

**Closed** 2018-01-30 18:00 UTC
