### ISSUE TITLE
NOT displayed Authenticator BROKEN

### ISSUE THREAD

**Issue by zetb612** [Sneezry/authenticator#224] opened 2018-01-28 15:27 UTC
Google Chrome not displayed cod

console: 
Uncaught ReferenceError: browser is not defined at popup.js:60

http://i.piccy.info/i9/f48647cfab9ffe166c55d8ef9112b8d5/1517153210/12668/1216841/auth_no.jpg

**Comment by mymindstorm** [comment] 2018-01-28 15:28
This is a duplicate of #223

**Comment by jokkerrr** [comment] 2018-01-28 15:36
Привет! у меня тоже пустой.....как установить старую версию?помощь-мне нужна помощь!!!

**Comment by zetb612** [comment] 2018-01-28 16:02
How long does it take to fix the error?

**Comment by mymindstorm** [comment] 2018-01-28 16:06
I don't really know how long it will take, probably somewhere between 12-24 hours plus the time it take for the extension to update

**Comment by zetb612** [comment] 2018-01-28 16:10
Software release life cycle:
Beta
RTM
https://en.wikipedia.org/wiki/Software_release_life_cycle

**Comment by Patr1ckCam3gu1ng** [comment] 2018-01-28 16:32
I also got this issue.

```
Uncaught ReferenceError: browser is not defined
    at popup.js:60

document.getElementById('menuTranslate').innerHTML += browser.i18n.getMessage('translate');
```

**Comment by Sneezry** [comment] 2018-01-28 20:56
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.

**Closed** 2018-01-28 22:31 UTC
