### ISSUE TITLE
authenticator stops working 

### ISSUE THREAD

**Issue by bphyak** [Sneezry/authenticator#250] opened 2018-01-28 19:43 UTC
Dear support team
suddenly authenticator stops working.i dn't have backup & apps functions are not working.plz hlp me

**Comment by diposs** [comment] 2018-01-28 19:53
document.getElementById('menuTranslate').innerHTML += browser.i18n.getMessage('translate');

**Comment by wolffuego** [comment] 2018-01-28 20:10
authenticator stops working
Is there any solution for this problem for now, is pass away  now couple of hours ant nothing resolved or some updates of possible time of resolving issues!!!

**Comment by Bizzledeans** [comment] 2018-01-28 20:24
My codes are blank. Any help appreciated. I cant trade without them.

**Comment by santaklouse** [comment] 2018-01-28 20:28
+1 
maybe this is a reason: https://goo.gl/WmXeJa

**Comment by jollanar24** [comment] 2018-01-28 20:37
My codes are blank. Any help appreciated.

**Comment by Sneezry** [comment] 2018-01-28 20:51
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.

**Comment by dungeon9x123** [comment] 2018-01-28 20:53
if authenticator fix . Can my key will restore ?
please help me ! i'm not backup ! i've 1.1 bitcoin on exchange please help me

**Comment by jollanar24** [comment] 2018-01-28 20:57
Hi @Sneezry  do we have just to wait?  it's a very sensible case here

**Comment by jollanar24** [comment] 2018-01-28 20:58
@dungeon9x123 @Bizzledeans  same case as i guess we hope that this extension return back sooner

**Comment by Sneezry** [comment] 2018-01-28 21:04
4.20 has been released, your extension should be upgraded automatically.

If you need upgrade immediately, open chrome://extensions/, check Developer mode, then click Update extensions now.

<img width="803" alt="qq20180129-050406 2x" src="https://user-images.githubusercontent.com/1621293/35487026-dead6726-04b1-11e8-8cd1-bfc60a306df9.png">

**Comment by jollanar24** [comment] 2018-01-28 21:59
Thank you @Sneezry

**Closed** 2018-01-30 17:56 UTC
