### ISSUE TITLE
My authenticator does not show. help me pls!

### ISSUE THREAD

**Issue by dinhhieu90** [Sneezry/authenticator#236] opened 2018-01-28 17:40 UTC

**Comment by dinhhieu90** [comment] 2018-01-28 17:49
![auth](https://user-images.githubusercontent.com/35898460/35485184-4b87c892-048e-11e8-9903-a55c69d97f98.JPG)

**Comment by mymindstorm** [comment] 2018-01-28 17:52
Duplicate of #223

Your codes are safe, fix coming soon

**Comment by Sneezry** [comment] 2018-01-28 20:54
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.

**Closed** 2018-01-30 17:56 UTC
