### ISSUE TITLE
Desktop Google Authenticator NOT working

### ISSUE THREAD

**Issue by thecryptolounge** [Sneezry/authenticator#229] opened 2018-01-28 16:57 UTC
Just used it a few minutes ago..... are my codes gone?!

**Comment by mymindstorm** [comment] 2018-01-28 16:57
Duplicate #223

Your codes are safe will be fixed soon

**Comment by thecryptolounge** [comment] 2018-01-28 16:58
thanks

**Comment by ricashrq88** [comment] 2018-01-28 18:06
yo tambien tengo el mismo problema no me genera ningun codigo,,,se han acabdo mis codigo..????

**Comment by Sneezry** [comment] 2018-01-28 20:54
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.

**Comment by thecryptolounge** [comment] 2018-01-28 21:05
Thank you!!!

**Comment by Sneezry** [comment] 2018-01-28 21:10
4.20 has been released, your extension should be upgraded automatically.

If you need upgrade immediately, open chrome://extensions/, check Developer mode, then click Update extensions now.

<img width="803" alt="qq20180129-050406 2x" src="https://user-images.githubusercontent.com/1621293/35487026-dead6726-04b1-11e8-8cd1-bfc60a306df9.png">

**Closed** 2018-01-30 18:01 UTC
